### ISSUE TITLE
Don't manage to use it, update button is not displayed

### ISSUE THREAD

**Issue by vricosti** [Inqnuam/HackinDROM#8]
Hi,
I am launching HackinDROM v2.1.4 on Monterey from Xcode (but I also tried from the dmg with the same results) and I cannot 
click on Update. When I try to display the OC version I have the following versions:

sharedData.OCv = 0.7.8
EFI.OCv = 0.8.3

is sharedData.OCv supposed to be the latest version of OpenCore retrieved from internet ?
How am I supposed to use this software ?
PS: The ssd used for macOS also has a linux install and that's why it's written linux instead of macOS 

Thanks

![Screenshot 2022-12-18 at 12 02 00](https://user-images.githubusercontent.com/80467769/208294745-4d25ebc6-564a-42dd-bcf3-5204dcb00b4a.png)
![Screenshot 2022-12-18 at 12 00 48](https://user-images.githubusercontent.com/80467769/208294738-bd697e69-6ccd-479a-8f12-9e7b70348ac6.png)

**Comment by Inqnuam** [comment]
Hello,
If you are trying to update your EFI:
There is a complete guide by @CaseySJ  on [tonymacx86's thread](https://www.tonymacx86.com/threads/hackindrom-app-for-opencore-efi-creation-and-update.312176/)
I guess you need [Option 2 update method](https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.316533/page-3524#post-2310939)
